CREATE USER DB_USER with encrypted password 'DB_PASSWORD';
CREATE DATABASE DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE DB_NAME TO DB_USER;
\c DB_NAME
GRANT ALL ON SCHEMA public TO DB_USER;
ALTER SCHEMA public OWNER TO DB_USER;